### ISSUE TITLE
Enemy name

### ISSUE THREAD

**Issue by babayarakosakomako** [prxvatescrxpts/true-sight#1]
I want to see enemy names. Is there a code for this? Or what do i need to change?

**Comment by aASDa213ASD** [comment]
Well the thing you are asking for is a true exploit that I've no clue about atm.
You can't see enemies, but I believe the client stores their names just somewhere because I've heard that this is possible to get them or at least see their pre-picked champion, something of that sort.
So - sorry for now but can't really help you there, only teammates.
